### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by MichaelAntonFischer** [weldan84/enpal-influx-evcc#2]
Hi,

I have started a fork on your project to make enpal bridge to modbus. Please tell me if you disagree with me using your code and licensing it as MIT.

Unfortunately, your repo doesn't state any license. 

Regards,
Michael

**Comment by dwwe2017** [comment]
You have my permission. Have fun 👍

**Comment by dwwe2017** [comment]
You have my permission. Have fun 👍

**Comment by weldan84** [comment]
You have my permission. Good luck with development. Best regards, Daniel Am 21.05.2024 14:50 schrieb MichaelAntonFischer ***@***.***>:
Hi,
I have started a fork on your project to make enpal bridge to modbus. Please tell me if you disagree with me using your code and licensing it as MIT.
Unfortunately, your repo doesn't state any license.
Regards,
Michael

**Comment by MichaelAntonFischer** [comment]
Modbus was too annoying, but creating a virtual meter worked. Thank you for giving me the right hints to finally integrate Enpal in my home automation.

**Comment by MichaelAntonFischer** [comment]
Just a heads-up my solution is working fine, with cfos. The custom http/json meters might be interesting for other home automations as well:

https://github.com/MichaelAntonFischer/enpal-link
